name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    container: "swift:5.7"
    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: make setup

    - name: Generate the website
      run: make generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: rei315/rei315.github.io
        publish_branch: master
        publish_dir: ./Output
